version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    ports:
      - "8000:80"  
    volumes:
      - .:/var/www/html
      - ./database/database.sqlite:/var/www/html/database/database.sqlite
    environment:
      - APP_ENV=local
      - APP_URL=http://localhost:8000
      - APP_DEBUG=true
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/database/database.sqlite  
      - SESSION_DRIVER=cookie
      - SESSION_DOMAIN=localhost
      - SANCTUM_STATEFUL_DOMAINS=localhost:8000  
      
    networks:
      - laravel

networks:
  laravel:
    driver: bridge